openapi: "3.0.0"
# servers:
#   - url: https://collector-service.lbry.tv
#     description: Production server
#   - url: https://collector-service.dev.lbry.tv
#     description: Development server
info:
  title: Advanced Metrics Collector
  version: "0.0.1"

paths:
  /api/v1/events/video:
    post:
      summary: Create a video buffering event
      responses:
        "200":
          description: event created
        "400":
          description: parameter error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"

components:
  schemas:
    URL:
      description: LBRY content URL
      type: string
      pattern: ^lbry://.+
    Event:
      type: object
      required:
        - client
        - type
        - data
      properties:
        data:
          oneOf:
            - $ref: "#/components/schemas/Buffering"
            - $ref: "#/components/schemas/PlaybackStart"
          discriminator:
            propertyName: type
            mapping:
              buffering: "#/components/schemas/Buffering"
              playback_start: "#/components/schemas/PlaybackStart"
        client:
          type: string
          description: unique anonymized client identifier
        device:
          type: string
          nullable: true
          description: client device
          enum:
            - web
            - android
    Buffering:
      type: object
      required:
        - url
        - position
      properties:
        url:
          $ref: "#/components/schemas/URL"
        position:
          type: integer
          description: position in stream, milliseconds
          minimum: 1
        duration:
          type: integer
          description: duration of the buffering event, milliseconds
          minimum: 1
        stream_duration:
          type: integer
          description: stream duration, seconds
          minimum: 1
        stream_bitrate:
          type: integer
          description: media bitrate, bits/sec (if known)
          minimum: 1
    PlaybackStart:
      type: object
      required:
        - url
        - time_to_start
      properties:
        url:
          $ref: "#/components/schemas/URL"
        time_to_start:
          type: integer
          description: time before playback started, milliseconds
        stream_duration:
          type: integer
          description: stream duration, seconds
        stream_bitrate:
          type: integer
          description: media bitrate, bits/sec (if known)
