[psql]
  dbname = "collector"
  host   = "localhost"
  port   = 5433
  user   = "collector"
  pass   = "ZnPfJ!4vTb-nURv8M!JkkuAcjYLYbkiX"
  blacklist = ["migrations", "other"]
  sslmode = "disable"
  testdbname = "collector_test"
