version: 2
jobs:
  test:
    docker:
      - image: lbry/lbrytv-ci:latest
      - image: lbry/lbrynet-tv:latest
        environment:
          SDK_LBRYUM_SERVERS: "spv4.lbry.com:50001"
      - image: postgres:11-alpine
        environment:
          POSTGRES_USER: lbrytv
          POSTGRES_PASSWORD: lbrytv
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: make test_circleci
      - run: git reset --hard HEAD
      - save_cache:
          key: go-mod-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg
            - /go/src
            - /go/bin

  publish-image:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - go-mod-cache-{{ checksum "go.sum" }}
      - run: curl -sLO https://git.io/goreleaser && chmod +x goreleaser
      - run: go get -u github.com/gobuffalo/packr/v2/packr2
      - run: ./goreleaser --rm-dist --snapshot
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: make image
      - run:
          name: Publish Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            make publish_image

  deploy-to-cluster:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: ./scripts/deploy.sh deployment api

workflows:
  version: 2
  integrate:
    jobs:
      - test
      - publish-image:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - feature/cluster
      - deploy-to-cluster:
          requires:
            - publish-image
