version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
      - image: lbryweb/lbrynet:latest
    environment:
      LW_LBRYNET: http://localhost:5279/
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: make test_circleci
      - save_cache:
          key: go-mod-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
  snapshot:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: make test_circleci
      - run: curl -sL https://git.io/goreleaser | bash
      - run: make snapshot
      - run:
          name: Build Docker image
          command: make image
  release:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: make test_circleci
      - run: curl -sL https://git.io/goreleaser | bash
      - run: make image
  publish-image:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            make publish_image

workflows:
  version: 2
  test:
    jobs:
      - test
  deploy-snapshot:
    jobs:
      - test
      - snapshot:
          requires:
            - test
      - publish-image:
          requires:
            - snapshot
          filters:
            branches:
              only: master
  release:
    jobs:
      - release
      - publish-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
          requires:
            - release
