version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
      - image: lbryweb/lbrynet:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: make test_circleci
      - save_cache:
          key: go-mod-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
  snapshot:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - run: go get ./...
      - run: go get github.com/GeertJohan/go.rice/rice
      - run: make embed
      - run: GOARCH=amd64 GOOS=linux go build -o dist/linux_amd64/lbryweb main.go
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: make image
  release:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
      - setup_remote_docker
      - run: curl -sL https://git.io/goreleaser | bash
      - run: make image
  publish-image:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go get ./...
      - run: go get github.com/GeertJohan/go.rice/rice
      - run: make embed
      - run: GOARCH=amd64 GOOS=linux go build -o dist/linux_amd64/lbryweb main.go
      - setup_remote_docker
      - run:
          name: Publish Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            make publish_image

workflows:
  version: 2
  deploy-snapshot:
    jobs:
      - test
      - publish-image:
          requires:
            - test
          filters:
            branches:
              only: master
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - publish-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
          requires:
            - release
