name: CI

on: push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up containers
        run: docker-compose up -d lbrynet postgres postgres-collector

      - name: Check running containers
        run: docker ps -a

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Prepare for tests
        run: |
          go get golang.org/x/tools/cmd/cover
          go get github.com/mattn/goveralls
          go run . db_migrate_up
          go run ./app/collector db_migrate_up
          scripts/wait_for_wallet.sh

      - name: Test
        run: |
          go test -covermode=count -coverprofile=coverage.out ./...
          goveralls -coverprofile=coverage.out -service=circle-ci -ignore=models/ -repotoken ${{ secrets.COVERALLS_TOKEN }}

  publish-image:
    name: Release Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    env:
      GOROOT: /usr/local/go
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Get version
        id: version
        run: echo "::set-output name=version::$(git describe --tags)"

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Get goreleaser
        run: >
          curl -sLO https://github.com/goreleaser/goreleaser/releases/download/v0.140.0/goreleaser_Linux_x86_64.tar.gz &&
          tar xfz goreleaser_Linux_x86_64.tar.gz && chmod +x goreleaser

      - run: go get github.com/gobuffalo/packr/v2/packr2@v2.7.1
      - run: ./goreleaser --rm-dist --snapshot

      - name: Push docker image to production
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lbry/lbrytv
          tags: latest,sha-${{ steps.slug.outputs.sha7 }},${{ steps.version.outputs.version }}
          tag_with_ref: true
          tag_with_sha: true

      - name: Push docker image to dev
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lbry/lbrytv
          tags: latest-dev,sha-${{ steps.slug.outputs.sha7 }},${{ steps.version.outputs.version }}
          tag_with_ref: true
          tag_with_sha: true

      - name: Deploy
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
        uses: octokit/request-action@v2.x
        id: deploy
        with:
          route: POST /repos/:repository/dispatches
          repository: lbryio/lbrytv-deployment
          event_type: deploy-lbrytv
          client_payload: |
            tag: sha-${{ steps.slug.outputs.sha7 }}
            ref: ${{ github.ref }}
            service: lbrytv-api
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_REPO_TOKEN }}
