name: Test

on:
  push:
    branches: [feature/git-actions]
  # pull_request:
  #   branches: [feature/git-actions]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up containers
        run: docker-compose up -d lbrynet postgres

      - name: Check running containers
        run: docker ps -a

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Prepare for tests
        run: |
          go get golang.org/x/tools/cmd/cover
          go get github.com/mattn/goveralls
          go run . db_migrate_up
          scripts/wait_for_wallet.sh
      - name: Build
        run: go build -v .

      - name: Test
        run: |
          go test -covermode=count -coverprofile=coverage.out ./...
