name: Test

on:
  push:
    branches: ["feature/git-actions"]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up containers
        run: docker-compose up -d lbrynet postgres

      - name: Check running containers
        run: docker ps -a

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Prepare for tests
        run: |
          go get golang.org/x/tools/cmd/cover
          go get github.com/mattn/goveralls
          go run . db_migrate_up
          scripts/wait_for_wallet.sh

      - name: Test
        run: |
          go test -covermode=count -coverprofile=coverage.out ./...
          goveralls -coverprofile=coverage.out -service=circle-ci -ignore=models/ -repotoken ${{ secrets.COVERALLS_TOKEN }}

  publish-image:
    name: Release Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' || 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - run: curl -sLO https://git.io/goreleaser && chmod +x goreleaser
      - run: go get -u github.com/gobuffalo/packr/v2/packr2
      - run: ./goreleaser --rm-dist --snapshot

      - name: Release Production Docker Image
        if: github.ref == 'refs/heads/feature/git-actions'
        # if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lbry/lbrytv
          tags: latest
          tag_with_ref: true

      - name: Release Dev Docker Image
        if: github.ref == 'refs/heads/feature/git-actions'
        # if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lbry/lbrytv
          tags: latest-dev
